name: "CE-Boostup-XIII"

volumes:
     database_data:


networks:
     default:
          driver: bridge

services:
     # -------------------------------------------------------
     #  Database Service
     # -------------------------------------------------------

     database:
          container_name: CE-Boostup-XIII-Database
          image: postgres
          deploy:
               resources:
                    limits:
                         cpus: "0.50"
                         memory: 500M
                    reservations:
                         cpus: "0.25"
                         memory: 100M
          environment:
               POSTGRES_USER: ${DB_USERNAME}
               POSTGRES_PASSWORD: ${DB_PASSWORD}
               POSTGRES_DB: ${DB_NAME}
          ports:
             - 5432:5432
          volumes:
             - database_data:/var/lib/postgresql/data
          restart: always

     # -------------------------------------------------------
     #   Backend Service
     # -------------------------------------------------------

     backend:
          container_name: CE-Boostup-XIII-Backend
          build: CE-Boostup-XIII-Backend
          environment:
               IS_DEVELOPMENT: ${IS_DEVELOPMENT}
               PORT: 3000

               FRONT_HOST: ${PROD_FRONT_HOST}

               DB_HOST: "CE-Boostup-XIII-Database"
               DB_PORT: 5432
               DB_USERNAME: ${DB_USERNAME}
               DB_PASSWORD: ${DB_PASSWORD}
               DB_NAME: ${DB_NAME}

               MAIL_HOST: ${MAIL_HOST}
               MAIL_PORT: ${MAIL_PORT}
               MAIL_USER: ${MAIL_USER}
               MAIL_PASS: ${MAIL_PASS}
          deploy:
               resources:
                    limits:
                         cpus: "0.50"
                         memory: 500M
                    reservations:
                         cpus: "0.25"
                         memory: 100M
          ports:
             - 3000:3000
          depends_on:
             - database
          restart: always

     # -------------------------------------------------------
     #   Frontend Service
     # -------------------------------------------------------

     frontend:
          container_name: CE-Boostup-XIII-Frontend
          build:
               context: CE-Boostup-XIII-Frontend
               args:
                    VITE_API_HOST: ${PROD_BACK_HOST}
                    VITE_BACK_HOST: "CE-Boostup-XIII-Backend"
          environment:
               IS_DEVELOPMENT: ${IS_DEVELOPMENT}
          deploy:
               resources:
                    limits:
                         cpus: "0.50"
                         memory: 500M
                    reservations:
                         cpus: "0.25"
                         memory: 100M
          ports:
             - 3001:3001
          restart: always

     # -------------------------------------------------------
     #   Compiler Service
     # -------------------------------------------------------

     compiler:
          container_name: CE-Boostup-XIII-Compiler
          build: CE-Boostup-XIII-Compiler
          environment:
               IS_DEVELOPMENT: ${IS_DEVELOPMENT}
          deploy:
               resources:
                    limits:
                         cpus: "0.50"
                         memory: 500M
                    reservations:
                         cpus: "0.25"
                         memory: 100M
          ports:
             - 3002:3002
          restart: always
