name: Generate PlantUML SVG and Save Image

permissions:
     contents: write

on:
     push:
          branches:
               - main

jobs:
     generate-plantuml-svg:
          runs-on: ubuntu-latest

          steps:
               - name: Checkout repository
                 uses: actions/checkout@v2

               - name: Gen image
                 run: |
                      sudo apt install graphviz
                      wget https://github.com/plantuml/plantuml/releases/download/v1.2025.1/plantuml-1.2025.1.jar
                      java -jar plantuml-1.2025.1.jar -tsvg Plan.pu

               - name: Commit and push the generated SVG
                 env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 run: |
                      git config --global user.name "GitHub Actions"
                      git config --global user.email "actions@github.com"
                      git add Plan.svg
                      git commit -m "Add generated Plan.puml SVG" || echo "No changes to commit"
                      git push
