name: Generate PlantUML SVG and Save Image

permissions:
  contents: write

on:
  push:

jobs:
  generate-plantuml-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gzip

      - name: Generate SVG file from Plan.puml
        run: |
          base64_plan=$(cat Plan.puml | gzip | base64)
          plantuml_url="https://www.plantuml.com/plantuml/svg/$base64_plan"
          curl -o generated_plan.svg "$plantuml_url"
          echo "SVG generated and saved as generated_plan.svg"

      - name: Commit and push the generated SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add generated_plan.svg
          git commit -m "Add generated Plan.puml SVG" || echo "No changes to commit"
          git push
