name: generate plantuml

on:
  push:

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        clean: true

    - name: Generate PlantUML diagrams
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: diagram
        message: Render PlantUML files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
