name: Generate UML Diagram

on:
     push:
          paths:
               - "**.puml"
     workflow_dispatch:

jobs:
     generate-diagram:
          runs-on: ubuntu-latest

          steps:
               - name: Checkout repository
                 uses: actions/checkout@v2

               - name: Install PlantUML
                 run: sudo apt-get install -y plantuml

               - name: Generate PNG
                 run: plantuml Plan.puml -tpng

               - name: Commit and push changes
                 run: |
                      git config --global user.name "GitHub Actions"
                      git config --global user.email "actions@github.com"
                      git add Plan.png
                      git commit -m "Update UML diagram"
                      git push
